### ISSUE TITLE
Could not find harp classes file. HARP dataset will not work correctly.

### ISSUE THREAD

**Issue by nimra008** [MICLab-Unicamp/e2dhipseg#6]
I'm new to this. When I try to execute python run.py this message shows up 
PS C:\Users\Dell\Desktop\medical image\hippodeep> python run.py
WARNING: Could not find harp classes file. HARP dataset will not work correctly.
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\medical image\hippodeep\run.py", line 23, in <module>
    from get_models import get_models
  File "C:\Users\Dell\Desktop\medical image\hippodeep\get_models.py", line 9, in <module>
    from unet import UNet
  File "C:\Users\Dell\Desktop\medical image\hippodeep\unet.py", line 11, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

**Comment by dscarmo** [comment]
@nimra008 Hi, the warning shouldn't be a problem, your error is actually in the from collections import Sequence line. You are using a newer version of Python while the code is a little bit old. I think it should work with Python 3.9 or lower. If it doesn't I can try to help you more

**Comment by dscarmo** [comment]
Due to no activity I am closing this issue, let me know if you need any extra help.
